---
title: "Working with a Graduate Adviser"
format:
  html:
    page-layout: full
    toc: true
sidebar: true
---
Really? A user's manual to your adviser? My goal as a faculty member (and more specifically as an adviser) is to do everything I can to be a support for you during your time (and oftentimes after!) as a graduate student. There's a few things you can do to help me (or your adviser if it's someone else) do the job well.

The usual caveats apply, however - your mileage may vary, and these are my personal opinions and should not be taken as those of my employer or as policy associated with my roles in the department and university.

## My Expectations

First off, the tl,dr for my advisees. These are some of my baseline expectations of how we'll work together in our advising relationship. I am always open to your suggestions and feedback, but I'm sharing so you have a sense of what I am looking for and expecting of you:

1. **Apply Yourself:** You're in graduate school to push yourself and to develop the skills necessary to be an independent decisionmaker. As an adviser, I see my role as being there to help you accomplish your goals, but I need to see you consistently applying yourself. Put plainly, I'm here to help, but I also need to see you helping yourself.
2. **Ask Questions:** I need you to ask questions - there are no silly questions! This helps me to help you, but also provides me with information about what's on your mind or how you're thinking about things.
3. **Communicate Proactively:** I like to head off problems or issues early. If you are feeling behind, struggling, or need help, please reach out early, rather than letting the issue linger or grow. I promise to do my best to listen without judgement and to work in a constructive way to support you.
4. **Prepare for our Meetings:** Please come prepared for our meetings - if you have something you'd like me to read or look at in advance, please send it well in advance of our meeting (24-48 hours, minimum). I am happy to read short things (less than a page or so) during meetings, but if you plunk down a thesis chapter and ask me for feedback, I'm not going to be able to provide feedback while you wait! Please come prepared to meet so that we can maximize our time together. If you find that you're not ready to meet, then let's just reschedule our meeting.

## Master's Students: What's the role of an academic adviser? A capstone adviser?

I find that a lot of Master's students are oftentimes confused by the difference between an academic adviser and capstone adviser. In our Master of Urban Planning program, these are two distinct roles, however by the end of your time in the program, they may be played by the same person (confused yet?!).

### Academic Adviser
When you enter the program as a Master's student, you're assigned a faculty **academic adviser** whose responsibility it is to help you develop a plan of study, select classes, and navigate any paperwork or petitions that impact your role as a graduate student. Our department attempts to match students with faculty academic advisers based upon overlap in areas of interest (based upon what you write in your application materials), but in general, all faculty should be qualified to help students develop their plan of study and navigate basic institutional systems. 

An academic adviser may also be required to provide letters of recommendation or support for competitive funding opportunities like campus or external fellowships. The role of your academic adviser is particularly important during your first year of study, as you seek to get your bearings and navigate expectations for graduate studies. 

### Capstone Adviser
For our Master's students, **capstone advisers** focus on providing substantive advice, feedback, and guidance on the capstone completed during the second year of study. This involves becoming familiar with your proposed work, signing off on your proposal, providing oversight and guidance throughout the capstone, and serving as the final reviewer and certifier of our capstone deliverables (manuscript and poster). It's your responsibility to identify which faculty will serve as your capstone adviser - you have to ask and they have to agree to work with you. As with so many things, proaction and clear communication is the key to building the relationship and commitment with the faculty you'd like to work with.

In some cases, your existing academic adviser is the natural fit for your capstone adviser. In other cases, you may choose to identify a different faculty member to serve as your capstone adviser. Selecting a capstone adviser doesn't automatically change who your academic adviser is, though. Many students ultimately make the choice to switch their official academic adviser to be the person who is serving as their capstone adviser - this gives you a "one stop shop" for academic and capstone advising in your second year. It's ultimately up to you if you choose to consolidate these roles or prefer to keep them separate. Whatever you choose to do, make sure both advisers know of your choice, and make sure the Director of Graduate Studies also knows so that we can update our records and communicate with the correct person for matters related to your academic advising and/or capstone.

## What's the role of a Ph.D. supervisor?

For those students who are beginning a Ph.D. program, it's important to note that the role of a Ph.D. supervisor is oftentimes different than the role of an academic or capstone adviser when you were a Master's student. In most cases, the role of a Ph.D. supervisor is far more active in shaping your experience and education at the doctoral level. That individual has made a commitment of time, attention, and financial resources to support your training as a doctoral student. 

Early during your time in the program, the adviser's role is to help you develop an initial plan of study, select classes, and oftentimes to spend time talking with you to get to understand your research, your mindset, and your goals for completing a Ph.D.. Your adviser may also get you involved early on in research projects or grant writing for existing projects. During this phase, you are the quintessential apprentice, working frequently alongside your adviser while also pursuing your own research agenda and building the skills and perspectives needed to pursue your work.

### Plan of Study
In our Ph.D. program, you will undertake an independent study with your adviser during your first semester to flesh out your initial plan of study and to begin work on two literature reviews that focus on knowledge domains related to your areas of interest. Advisers will take different approaches to these early relationship-building activities - some may be more passive and simply look to provide feedback after you've spent time working towards these deliverables, while others may be more active in shaping and reviewing your interim work. It's up to you to talk and communicate in order to develop shared expectations during this early getting to know you period. At the end of your first year, you'll have a plan of study "defense" - this is basically a review of what you've done and a more formal opportunity for your adviser and another faculty member to provide you with feedback on your evolving plans.

As you advance during your time in the program, your adviser's role will evolve as well. The next major milestones to focus on will be the completion of your literature reviews and the iterative evolution of your plan of study document. The idea here is that by bringing together substantive knowledge in your area of expertise through the literature reviews with your own reflection, goal setting, and claim making about your chosen domains of intellectual expertise, that these things together will serve as foundational documents which will be used as part of your qualifying exam.

### The Qualifying Exam
In our department, we offer two pathways to qualifying - a research paper pathway and an examination pathway. For those students who are working with (or considering working with) me, please note that I have a strong preference for using the examination pathway for the qualifying exam. In my opinion, the examination (if done the way I prefer to do it) serves as a more holistic opportunity to examine and provide feedback on your identity and approach as an academic. Typically, we'll design the examination to test your expertise at the intersection of knowledge domains you lay claim to, your chosen expertise with regards to methodology, and expertise with regards to theory related to your work. To my mind, the best exam questions help you to **grow into** this identity, which you'll carry forward into your future work.

Many advisees get nervous when they hear the word *exam* used in this context. While it's very true that there are stakes associated with the results of this exam (that can include dismissal from the program if results are unsatisfactory), know that your adviser should not let you schedule your exam until they are confident that you can not just pass it, but knock it out of the park. Much of the feedback you will receive following your exam will focus on how to continue to shape your scholarly identity and research based upon what you've shared with us. We will also typically be talking about and thinking about implications of your writing in your exam for your dissertation research.

The other role your adviser will play during this stage is helping you to select exam committee members strategically, and thinking about how many of these members may also be aligning with your dissertation committee. You should have thoughts in mind, and also be open to feedback, not only on what you see committee members bringing individually and as an ensemble to your work, but also your understanding of the interpersonal dynamics between committee members. Please know that we as advisers are also thinking carefully about this, as we may have prior experience with how other members tend to interact with each other, who is likely to get along, and who might add more complication to your committee. Just understand that it's your process and your committee, but also understand the reasons we may give certain types of feedback.

In some cases, we may suggest a joint preliminary exam review and dissertation proposal defense, but in most cases, we want you to have a break and a chance to think and reflect in between the two. While there's a lot more to say about the dissertation proposal and defense, my goal for my advisees is to move relatively quickly from one to the other - it's easy to get stuck in a kind of doldrums in between your exam and proposal defense (speaking from personal experience). 

### Dissertation Proposal Defense
The final steps - the dissertation proposal defense and dissertation defense are really all about constructive feedback. The dissertation proposal defense is basically our last change to really do substantive shaping of your dissertation project. Yes, again, there's a gatekeeping function here in terms of go/no-go on the dissertation research, but your adviser should set expectations that you have met individually with your other committee members so they are on board with the general concept of your dissertation proposal before the defense.

From an advising perspective, the proposal defense is really the chance for us to collaborate on giving you feedback, and for you to get feedback consolidated all in one place. It's also a chance to get your committee all on board with a shared set of expectations for your work. During this process, your adviser should help mediate, and should help collect and organize the feedback which you have received. They may help identify committee members who are interested (or feel the need to) give particular advice or support around a particular area of your work, and will help to develop a collective sense of your timeline and the activities that will happen as you are working through your dissertation.

You may leave your proposal defense with a punchlist of issues to resolve or questions to engage with, but you should also leave feeling empowered to move forward (independently) with your work. Then it's off to the races (or literally off to the research)!

### The Dissertation Defense
The final stage here is your dissertation defense. Of course, you will meet regularly with your adviser while you're performing the dissertation research, and should meet and share writing regularly as you write up your dissertation. Your adviser will also help determine when you should share chapters or sections of your dissertation manuscript with other committee members. Some may commit to reading along the way and providing feedback, and others may focus on reading later on when you have a complete manuscript ready to go in advance of your defense.

During this stage, you should confirm with your adviser what roles you want committee members to play - providing feedback on specific areas like methods, theory, or your discussion. You should also talk with your adviser about how to share interim findings through publications, reports, op-eds, and other venues.

The defense is a big moment - a public celebration of your work, and also a final moment for your adviser and the committee to help you polish your presentation. Like the proposal defense, your adviser will likely do less speaking and more listening so that your committee members can weigh in and you can focus on listening to what they have to say. Behind the scenes, your adviser has likely had some pre-conversation with committee members about your dissertation manuscript, and has some sense of the feedback you will receive. 

My goal for the end of a students' defense is to be able to hand them a "punchlist" of specific items to address, with some sense of an order of priority. If specific committee members feel that they need to revisit or review items in your punchlist, I will try to itemize that and then will confirm with you later on that this has been done. Following your defense, we will work to address items in your punchlist based upon their priority and will then focus on final review for submission and certification.

## After You Graduate

I like to think of myself as an adviser for life, and enjoy keeping in touch with many of my graduate advisees after they complete their degrees. Early on after students graduate, this typically involves letters of recommendation for jobs or education, but for some advisees it's involved more continued conversation about personal and professional goals and development. The main thing is to keep in touch (if you want to), and don't hesitate to reach out or ask for advice. It may take a little longer for me to get back to you, but I love to learn what's going on, to help out, and to learn more about who you are and to celebrate your accomplishments!