---
title: "Navigating a Move to Chambana"
format:
  html:
    page-layout: full
    toc: true
sidebar: true
---

I remember how overwhelming it was navigate a move to Champaign in 2011. Over the years, I've amassed some resources that I often share with incoming faculty, visiting scholars, and students to help ease that transition.

The usual caveats apply, however - your mileage may vary, and these are a selection of personal recommendations. Mentions or links to certain businesses do not equal an endorsement.

## Housing

It's hard to encapsulate housing since this is such a personal process. I rented a house for several years before buying. I know plenty of new faculty who purchased a house when they moved to the area. While large landlords dominate the student housing market, for individuals who are looking for non-student housing, you are likely to have more luck with smaller landlords.

For incoming faculty, if you're able to come to town, I think that will help greatly with identifying neighborhoods and housing options that make sense for you. At a minimum, have someone here go check things out for you before you commit!

I've had a good experience with [State Farm / John Caywood](https://www.statefarm.com/agent/us/il/champaign/john-caywood-1dbh14npnal) for insurance - they've always been responsive and easy to work with.

## Schools

On schools, Champaign and Urbana are in separate school districts.

-   **Urbana:** [Urbana School District 116](https://usd116.org) uses a neighborhood schools model (so attendance areas determine school choice). Arguably the most popular school particularly for faculty kids is Leal elementary (and therefore lots of faculty live in the area around the school, which is also relatively convenient to campus.

-   **Champaign:** [Champaign Unit 4 School District](https://www.champaignschools.org) uses a school lottery system. This means that you have the opportunity to state a rank order preference from among all the schools in the city (and also receive some extra preference for the schools closest to your house), and then the school district uses this information to assign your school.

-   We've had a great experience with [Countryside School](https://www.countrysideschool.org/quicklinks) which is a private independent school focused on grades K-8.

## Groceries

There's multiple Schnucks, Meijer, etc. for everyday stuff. We use Aldi to buy our basic weekly items and then supplement with items from other stores as needed. For bulk purchasing, there's a [Costco](https://www.costco.com/warehouse-locations/champaign-il-1384.html) and [Sam's club](https://www.samsclub.com/club/champaign-il-sams-club/8197). Lots of other ethnic and specialty grocery places -- these are just the ones I tend to go to more frequently.

-   [Cheese and Crackers](http://www.crackerscheese.com) has a great cheese and deli selection. They also are the best option for high-quality fresh fish which is driven down from fish distributors in Chicago several times a week. They have an email list for what fish is in season. You order the day before and your fish is ready for pick up the next day.

-   [Art Mart](https://www.shopartmart.com) also has a great cheese and deli selection, quality wine (Todd can get you almost anything and is a pleasure to do business with), and they also have a great selection of higher-end kids toys, games, and books.

-   [Common Ground Food Co-Op](https://www.commonground.coop) is our local co-op option -- lots of local and specialty food. Its certainly a scene for us university types. Cooking classes, good curated wine selection, and [Chamanoy Knife Sharpening](https://www.facebook.com/champaignurbanaknifesharpening/) on some Saturdays.

-   [World Harvest Foods / Strawberry Fields Cafe](https://worldharvestfoods.com/strawberry-fields/) in Urbana has a good selection of international foods (far more specialized than what you can get in the grocery store).

-   [Fresh International Market](https://freshimarket.com) has a pretty good selection of Asian groceries, and a decent fresh section. I don't go here a lot, but do stock up on mushrooms, greens, rice, noodles, miso, etc. here.

-   [Bane Family Meats](https://www.banefamilymeats.com) -- local veterinarian turned small farmer who raises meat. He does home deliveries.

-   [Triple S Farms](https://www.triplesfarms.com) -- another good local meat purveyor - available through their website, at the Urbana farmer's market, and in other retail locations like the Coop.

-   [Old Time Meat and Deli](https://oldtimemeatanddeli.com) is a great butcher. They can also special order cuts or items for you.

-   [UIUC Meat Lab](https://meatandeggsales.illinois.edu) sells meat that has been produced on campus or through campus operations. Much of the butchery and retail is done by students, which is an bonus part of the meat lab experience.

-   [Prairie Fruits Farm](https://www.prairiefruits.com) has local goat cheese, goats milk gelato, and other specialty items. They have hours where you can go visit the goats which makes a great family trip. They also do [dinners](https://www.prairiefruits.com/calendar-and-tickets) that bring down chefs from Chicago, Saint Louis, and other regional markets to cook with local produce.

## Takeout / Dining Favorites

### Barbecue

-   [Black Dog Smoke and Ale House Champaign](https://www.blackdogchampaign.com/home-1) -- my preferred barbecue in town.

### Mexican

-   [Maize Mexican Grill](https://www.maizemexicangrill.com) -- my preferred Mexican food in town. They have a location on campus and in the student union, and one in downtown Champaign. Go downtown for a nice patio, table service, and excellent drinks.

-   [Huaraches Moroleon](https://www.smilepolitely.com/food-drink/huaraches_moroleon_is_an_urbana_gem/) in Urbana is also very good and has a great patio.

-   [Los Hidalguense Taco Truck](https://www.smilepolitely.com/food-drink/los_hidalguense_taco_truck_is_way_more_than_tacos/) is unassuming, but produces some of the best taqueria-style food in the region.

### Thai / Lao

- [Sticky Rice](https://stickyricechampaign.com) has an excellent selection of Lao and Thai dishes.

- [Y-Thai](https://www.universityymca.org/what-we-offer/y-thai-eatery) is one of my go-to on campus choices for a quick lunch.

### Korean

-   [San Maru](https://sanmarucu.square.site) does an excellent job with home-style Korean Food.

-   [Star BBQ](https://www.smilepolitely.com/splog/have-you-tried-the-all-you-can-eat-menu-at-star-bbq/) in Savoy has good all you can eat Korean BBQ specials.

### Vietnamese

-   [83 Vietnamese](https://www.83viet.com) with is right next door do San Maru is also excellent. Any special I've had there has been great.

### American

-   [Farren's Pub](https://www.farrenspub.com) -- best hamburgers in town.

-   [Seven Saints](https://www.sevensaintsbar.com) -- Best sliders and tomato soup in town.

-   [The Space](https://thespacecu.com/pages/menus) -- Smashburgers served on vintage plasticware from the '80s and '90s.

### Indian

-   [Himalayan Chimney](https://www.thehimalayanchimneyil.com/order) -- pretty good Indian food.

-   [Kohinor](https://www.kohinoorchampaign.com)

-   [Naya Indian Cuisine](https://nayaindiancuisineil.com)

-   If you are in Bloomington, you have to go to [Bloom Bawrachi](https://bloombawarchi.com) - they also accept online delivery orders to Champaign on the weekends.

### Pizza

-   [Papa Del's](https://www.papadels.com) pizza is probably the community favorite for pizza.

-   For Neapolitan style pizza, [Pizzeria Antica](https://anticachampaign.com) is the place to go.

-   [Flour and Fire Pizza](https://flourandfirepizza.com) Truck also makes a good wood fired pizza (Funghi is a must).

### Chinese

-   [Golden Harbor](https://www.goldenharboronline.com) -- Authentic Taiwanese and Chinese food.

-   [Rainbow Garden](https://rainbow-garden.com) -- Very solid Chinese-American menu.

### Japanese / Sushi

-   [Ishi and Kaori's Oven](https://www.smilepolitely.com/splog/lunch-at-ishi-is-seriously-excellent/) -- Small sushi bar with limited options, but they are all excelleng

-   [Sakenaya](https://www.sakanayarestaurant.com) -- Sushi

-   [Tenkyu](https://www.tenkyu.cafe) -- Izakaya-style dishes and ramen

### Sweet Things

-   [Jarlings Custard Cup](https://www.jarlingscustardcup.com) -- Frozen Custard (has drive through and is [Tom Hanks' favorite](https://www.wandtv.com/news/champaign-business-named-one-of-best-ice-cream-shops-in-u-s/article_8a9ab14a-ad91-11e9-a89e-d36a2c10bad4.html))

-   [El Oasis](https://www.facebook.com/El.Oasis.in.Urbana.IL/) in Urbana is a Mexican ice cream shop with an amazing assortment of flavors and treats.

-   [The New Sweet Indulgence](https://www.thenewsweetindulgence.biz) -- Bakery -- good place for cakes.

-   [Pandamonium Doughnuts](https://pandamoniumdoughnuts.wixsite.com/pandamoniumdoughnuts) - arguably the best place for unique artisinal doughnuts.

-   [Industrial Donut](https://www.industrialdonut.com) -- robotically cooked doughnuts with design your own flavor combinations.

-   [Hopscotch Bakery and Market](https://hopscotchmarket.com) -- excellent baked goods. I'm not a fan of their coffee, but your mileage may vary...

-   [The Literary](https://www.literarybookbar.com) -- Books, Coffee, Cocktails - what's not to love?

### To Drink

-   [Riggs Beer Company](https://www.riggsbeer.com) -- locally brewed German-style beer. Expansive outdoor seating, and very kid friendly. Good weekly calendar of food trucks. You can also reserve tables for events.

-   [Triptych Brewing](https://triptychbrewing.com) -- locally brewed beer. Smaller outdoor seating area and beer to go. Good weekly calendar of food trucks. Don't sleep on the pinball area in the back!

-   [Punch! Bar and Lounch](https://punchbarchampaign.com) is an above average hotel bar with a wide selection of mixed drinks.

-   [Alto Vineyards](https://altovineyards.net/our-locations#Champaign) -- yep, central Illinois wine is a thing! Patio with music on the weekends.

## News

-   I tend to get most of my local news from [Smile Politely](https://www.smilepolitely.com) which is a volunteer run information source.

-   [Chambanamoms.com](https://www.chambanamoms.com) is also a good source for all things kids.

-   The [Public I](https://publici.ucimc.org) is a citizen-run news source.

-   [WEFT 90.1](http://new.weft.org) community radio

-   [WILL / Illinois Public Media](https://will.illinois.edu)

-   [The News Gazette](https://www.news-gazette.com) is our (official) local newspaper

## Medical Care

Some of this will depend upon which insurance you elect -- our university plans are very good with the major medical facilities here.

-   **Doctor** - I've had a great experience with [Dr. Tegan McCormick](https://www.christieclinic.com/providers/445/Tegan-McCormick-DO/provider/) at [Christie Clinic](https://www.christieclinic.com) on Windsor in Champaign (internal medicine).

-   **Pediatrician** - I've had a great experience with [Dr. Alexis Orama](https://www.christieclinic.com/providers/427/Alexis-Orama-MD/provider/) at Christie Clinic on Windsor in Champaign.

-   **Emergency Care** - There's lots of convenient care facilities for minor things (we tend to use Christie on Windsor). For more emergencies, both [Carle](https://carle.org/locations/carle-foundation-hospital) and [OSF](https://www.osfhealthcare.org) have emergency rooms. **Pro-tip:** If you happen to need ER services for a kid, **go to Carle**. OSF isn't really set up for kids and will typically transfer you to Carle if there's an issue.

-   **Dentist** - I've been seeing [Dr. Mike Rufatto, DMD](https://www.ruffattodental.com) since I moved to Champaign. He's great and his practice also does a wonderful job with kids.

## Short Trips

-   [Casey Illinois](https://maps.app.goo.gl/4SuEc6Sc2C8xQ17p7) -- Holds multiple records for the worlds largest things.

-   [Kickapoo State Recreation Area](https://dnr.illinois.gov/parks/park.kickapoo.html) - nice way to spend a day, particularly by the tubing launch area

-   [Allerton Park](https://allerton.illinois.edu) -- near Monticello, IL. [3 Ravens](https://3ravens.pub) is a good place for lunch in town.

-   [Monticello Railway Museum](https://www.mrym.org) -- Amazing restored rail cars and the opportunity to ride on a steam locomotive.

-   [Homer Lake Forest Preserve](https://www.enjoyillinois.com/explore/listing/homer-lake-forest-preserve/) - decent hiking and nice way to spend an afternoon.

-   [Harvest Moon Drive in Theater](https://harvestmoondrivein.com) -- right outside Gibson City, IL. You can buy tickets online ahead of time. Typical concession-style food options available, but you can also bring your own food for a small fee.

## Slightly Longer Trips

### Chicago

Chicago recommendations really need their own page. Here's a few selections though.

#### To Do

Consider visiting the [Chicago History Museum](), the [Chicago Architecture Center](), or the [DuSable Black History Museum and Education Center](https://www.dusablemuseum.org). The [National Museum of Mexican Art](https://nationalmuseumofmexicanart.org) is also excellent.

#### Food

Chicago is a food city – you can learn a lot by visiting a range of eating establishments

-   [Jim’s Original](http://jimsoriginal.com): Polish Sausage

-   [Al’s #1 Italian Beef](https://www.alsbeef.com/chicago-little-italy-taylor-street): My preference is dipped with hot peppers.

-   [Bari Italian Foods](https://www.bariitaliansubs.com) - You want the Italian Sandwich from the deli in the back

-   [Girl and the Goat](https://www.girlandthegoat.com/chicago) or [Little Goat Diner](https://www.littlegoatchicago.com)

-   Jibarito Sandwich – a Chicago invention of the Puerto Rican community – in fact, Paseo Boricua would be a good neighborhood to visit too.

-   [Taqueria La Pasadita](http://www.pasadita.com) (Wicker Park) or [La Casa Del Pueblo](https://www.facebook.com/LACASADELPUEBLORESTAURANT/) (Pilsen)

-   [Yvolina's Tamales](https://www.facebook.com/yvolinastamales/): Wrapped in banana leaves. So good.

-   Devon Avenue is where to go for Indian food

### Saint Louis

-   [The City Museum](https://www.citymuseum.org): This place is wild, and while it's clearly intended for kids, there's a lot for adults to enjoy too.

-   [Salt + Smoke Barbecue](https://www.saltandsmokebbq.com): Somehow we found ourselves here on a night in December where the temperature was in the 70s. Pretty much everything we had was delicious. I wish we had been able to try the desserts, but our unseasonably warm evening turned into a scene from a disaster movie as severe weather ripped through the region. Very much worth a visit.

-   [Pappy's Smokehouse](https://www.pappyssmokehouse.com): Also excellent barbecue - I don't have a weather story about this place...

-   [The Fountain on Locust](https://www.fountainonlocust.com): Very beautiful ice cream parlor and bar with an excellent food menu too.

-   [Comet Coffee](http://cometcoffeestl.com): Their bakery produces one of the finest croissants I've ever had - many thanks to [Dr. Meaghan Kirkwood](https://www.meghankirkwood.com/about) for introducing this place.

### Louisville

-   [Muhammad Ali Center](https://alicenter.org)

-   [Kentucky Peerless Distilling Co.](https://kentuckypeerless.com)
