---
title: "Graduate Admissions"
format:
  html:
    page-layout: full
    toc: true
    toc-depth: 4
sidebar: true
---

In the recent past, I served as Director of Admissions for one of our department's graduate programs. During that time, I read and participated in deliberation on nearly 1,000 applications for admission to the program. I've served in other roles involving the review of applications from graduate students across our campus for fellowships, and have also designed and run several graduate fellowship programs for learned societies.

I want to share some general observations from what I've learned reading many applications, and also provide some pointers for what you as an applicant can do to help your application reviewers do their job.

The usual caveats apply, however - your mileage may vary, and these are my personal opinions and should not be taken as those of my employer or as policy associated with my roles in the department or university.

## How do we use your application?

While it's arguably pretty obvious what a graduate program application is, there's some nuance in how that application gets used once you submit it. The most central reason is obvious - to determine whether you will be admitted to the program you applied to. In some cases, your application may also be used for the purposes of assessing merit-based financial aid, may be used for internal nominations for fellowships, or may be used for assigning an academic adviser.

We rely upon different elements of your application for all of the purposes I mention above.

## What makes an application competitive?

Applications can be competitive for different reasons - clearly prior academic history and performance is often a strong indicator of future success. In professional programs, work history can also be an important criteria. In general, I typically look for some kind of sustained engagement that connects to the degree program. This sustained engagement could come in many ways - through your prior academic history and the work you did previously as a student; through your professional history; or through engagement undertaken in your personal life through volunteerism or service to boards or government.

I find that the most compelling applications can tell me a story about your past, present, and future, offering a clear vision for why you're seeking to pursue a particular degree, what the fit is that you see between your objectives and the degree program, and what you hope to accomplish during and after your time in the degree program. Applications that are both well-written and that show time and research about the program are likely to stand out.

Here are some of the *general* questions which I typically consider when reading a graduate application:

1.  **Are they qualified?:** Does this candidate meet our departmental criteria for admission? Do they meet the university's criteria? Are there any areas we may need to provide justification for (for instance a prior graduate degree of the same level in a similar field or a GPA that falls below our institutional minimums).
2.  **Do they understand what the degree does?:** Does the candidate seem to understand what the degree they're applying for is likely to offer with regards to professional and scholarly opportunities? Do they have a clear vision for their own goals for pursuing the degree?
3.  **Do they represent a good fit with our strengths?:** In looking primarily at your personal statement and statement of purpose, we're looking to see how your interests and stated goals fit with our understanding of our department's strengths. There are some times where highly qualified students may simply not be a good fit with a program because they want to work in an area a program is not strong in. For instance, if a highly-qualified student wants to pursue a professional career in urban design, but they apply to a program whose faculty's strength is in policy-based planning, there may simply be a lack of fit that will come up in our admissions deliberation.
4.  **Are they likely to be successful?:** Similar to the question of fit, I am typically looking for evidence that a student is likely to be successful in the program they are applying for. Success is qualified through how you (and your letter writers) frame your past, present, and future.
5.  **What unique perspectives do they bring?:** We want to build a cohort full of diverse and interesting students - while these things are typically not the make or break element of your application, providing an understanding of your unique perspective and unique life experiences can add important context to your application.

## How can I best represent myself?

Now that you have some sense of what admission committees are likely to be looking at, let's talk about how you might best represent yourself.

First off, make the most out of your statements. In the case of the graduate programs I work with, this includes a statement of purpose and a statement of personal history. The statement of purpose is essentially the keystone to all of your other application components. The statement of personal history helps us understand your trajectory and how your life experiences serve as context for your decision to pursue graduate studies and the goals you articulate. Many applications including ours include some additional short answer questions which also help us better understand your life experiences and other circumstances that may help us to contextualize your application. Thoughtful answers to these additional questions (and ones that do not simply restate things you have already said elsewhere in your statements) can often provide valuable context for our consideration - take the time to address these with care.

Of all these statements, the statement of purpose is (in my opinion) the most important component of the application. It is your best opportunity to provide context and framing for your other application materials. The remaining materials serve as evidence in support of the argument you're making. The statement of purpose is also where you can help your application reviewers understand these elements of your application - both in terms of things that you want to stand out, but also in terms of helping us have context for things like a weak GPA or a gap in work history, for instance.

Here are some common pitfalls I typically see that can undermine a graduate application statement of purpose:

1.  **Over reliance on chronology:** applicants often use their statements as a narrative version of their resume. The reality is that we already have your resume as part of your application materials - re-hashing your accomplishments and the names of institutions and workplaces without helping us understand why these things are significant or how they helped transform your thinking is wasting our time and attention. This does not mean that chronology can't be a useful tool, but avoid re-stating the superficial things we can already glean through your other application materials.
2.  **Under-emphasis on perspective:** students oftentimes want to present a very neutral picture of themselves. Vagueness often comes off as a lack of preparation, research, or understanding. While I'm not suggesting that you put every one of your quirks or hot takes in your application, providing a genuine sense of yourself and your perspective through your writing can help us greatly in our assessment of fit and our sense of what unique viewpoints you'll bring to our graduate programs.
3.  **Lack of attention to fit:** in an application cycle, an admission committee can go through hundreds of applications. Those applicants who demonstrate that they understand the program, its faculty, and its context help us greatly in answering the question of fit and preparedness. It's typically clear when an applicant is using very general text about the university or fit, or when they get basic facts wrong about our program or context. It's also typically very obvious when AI writing aids were used to compose narrative statements. These types of omissions, errors, and strategies are not likely to instantly disqualify an application, but they may influence our overall confidence in the application and preparedness for graduate studies.

So what can you do to represent yourself well?

1.  **Invest time in your statements:** These statements are the keystone of your application. Take the time to write a thoughtful and compelling narrative that speaks to your past, present, and future, demonstrates *why* you are choosing to pursue graduate studies, and that articulates your professional goals during and after you receive the degree. Don't leave us guessing why you're applying to the program.
2. **Address the prompts in supplemental personal statements:** Extending my point above, many graduate applications include supplemental personal statements that are sometimes optional and which ask for additional information about your life experiences and other experiences or attributes that might contextualize your application. Treat these (typically short) statements seriously and try not to repeat material which you have already highlighted elsewhere in your narrative statements. 
3.  **Choose letter writers judiciously:** Letters of reference will likely look different if you've just recently graduated from another degree program than if you've been working in the field for ten years. I would anticipate that a recent graduate would rely primarily upon letters of reference from faculty they worked closely with in a prior degree program. By contrast, I would anticipate that someone whose been working for ten years might rely more upon past or present supervisors for letters (hopefully with *at least* one letter from an academic reference). Regardless of who you select to write your letters, consider drawing upon these writers to address of cover different aspects of your history and professional experience.
3.  **Mention faculty:** mention faculty who you are particularly interested in working with. This helps us assess fit, and can help us make connections with these faculty or their current advisees throughout the admission process. If you are going to mention a faculty member in your application, it's also important to *tell us why* you see a connection to their work.
4.  **Address your weaknesses:** If you see weaknesses or things that may raise questions in your application, address them head-on particularly in your statements. The more questions we have that are not addressed, the less confidence we are likely to have in your overall application.
5.  **Proofread, proofread, proofread:** Spelling, grammar, and detail issues speak to your level of attention and commitment to representing yourself well. Taken individually, they are not likely to sink an application, but may influence our level of confidence in your preparedness for graduate studies.

## How can I identify my fit with a program?

A lot of my comments have focused on the question of *fit*. In addition to substantiating your qualifications for a graduate program, your application is arguing for your fit with the strengths of the program. This means that you need to do some due diligence prior to and during the application process to identify fit. Here's a few strategies:

1.  **Research:** Spend some time researching the programs you're interested in. I'd suggest not only looking at the names of the universities the program is in (of course some people apply to prestigious institutions because they are interested in the value of being associated with the name of that institution), but also in terms of the core strengths of the faculty in your area of study, what types of roles past and recent alumni are working in, where students coming into the program come from, and what types of support are available for your studies and professional development.
2.  **Contact:** Reach out to the admissions officer or graduate program director, or directly to current faculty, students, or alumni. In the case of program faculty, we are always happy to answer questions regarding the program. It may not be useful to contact a graduate program director and say *can I have more information on the program?* - generally, there's comprehensive information on our website, and we'll then write an email directing you to what you should have already read before reaching out. We may also be annoyed at the lack of specificity in your request. Instead, focus on more specific questions, or request the opportunity to have an informational conversation (and come ready with specific questions about the program).
3.  **Connect:** Use tools like LinkedIn and personal networks to identify program alumni, particularly those who you might already have connections with and ask them not only about their experiences with the program, but also who you should talk to within the program. They'll oftentimes be able to offer a unique perspective which you won't be able to get elsewhere.
4.  **Explore:** Spend some time sleuthing on the program and department's website. You can oftentimes find things like past thesis and dissertations completed by recent alumni, course syllabi, awards won by students, and engaged projects which classes have done with local communities. Taking time to do this kind of sleuthing can greatly inform your own application and materials.

## Special Considerations for Ph.D. Applicants

#### Connecting to Faculty

For Ph.D. students, all of the above is important, but it's particularly important to identify and reach out to a potential Ph.D. advisor before you submit your application. This advisor is not only an important portion of your doctoral studies, but ultimately, they're also the one ultimately making the commitment (intellectual and financial) to take you on. While sometimes these connections can be built after your application is submitted, having contact and assessing fit with an advisor before your apply may help you figure out which programs and advisers to prioritize. Checking out faculty websites isn't sufficient for assessing fit - talk with us, ask us about our work, ask us about our future agenda, and ask us about our advising style. Most importantly, ask us about our plans to take on a new advisee in the near future - this may save you time (and money!). You will likely be surprised at how much these conversations may shape your applications.

One important note here with regards to contacting faculty - in some cases, you may not get a response to a general request or inquiry about advising. Do not take a lack of response as a lack of interest. Many faculty including myself get multiple requests like this *per day*, and may not prioritize engagement given the many other things on our plates. Given the email burden which many faculty face, the best strategies for getting a response are to compel one - like much of my advice about the application process, form emails or emails lacking substance are more likely to receive low priority or no response. If you don't hear anything after making a request, it is okay to follow up (I think 7-14 days is an appropriate time after an initial advising inquiry email for a follow-up).

#### Thinking Holistically About Your Research

The Ph.D. is the terminal scholarly degree in most fields which qualifies an individual to independently conduct research that sustains and extends the field. There's a range of cultures in various academic fields for what evidence a prospective doctoral student needs to bring to the table to qualify their research projects and perspective.

For Ph.D. programs in urban planning or other applied social science areas, particularly those in the United States, we are typically interested in understanding at the application phase about the *big picture* research questions that are the types of questions which you may engage with other the course of your scholarly career. You may also have ideas for smaller research questions that you want to explore, particularly in something like a dissertation, but at the application phase, I am more concerned about the big picture.

Why the big picture and not your dissertation research? In many U.S. applied social science Ph.D. programs like planning, the curriculum typically involves around 2 years of preparatory coursework before a doctoral student takes a qualifying exam (to evidence their expertise in a particularly scholarly domain or domains) and a separate preliminary exam (dissertation proposal defense). It is likely that the question(s) you ask in your application may still be reflected in your dissertation proposal two years and many classes later, but I would expect that your ideas, perspectives, and methods would evolve greatly as a result of your experience as a doctoral student. Therefore, these smaller types of questions are less important at the application stage when compared to the big picture questions that can help to describe the conceptual domains associated with your work.