---
title: "The MUP Capstone"
format:
  html:
    page-layout: full
    toc: true
    toc-depth: 4
---
This documentation is designed to help my advisees and students in the Master of Urban Planning (MUP) program at University of Illinois at Urbana-Champaign to navigate the Master's capstone process. It is likely that while some of this information may be somewhat specific to this program, that individuals in other graduate programs, particularly those in other planning programs or other applied fields may find this information useful and transferable.

The usual caveats apply, however - your mileage may vary, and these are my personal opinions and should not be taken as those of my employer or as policy associated with my roles in the department and university.

## What is it?
Most graduate programs in planning require students to complete some kind of major project, workshop, studio, or work of research to substantiate their mastery of the field and ability to practice elements of their craft in an independent and comprehensive way. These experiences are typically 2 semesters long, require some form of sustained and independent engagement or work, and required some form of polished output targeted towards a public audience. At UIUC, we offer two primary pathways to completing this requirement - the completion of a Master's Project or the completion of a Master's Thesis.

In thinking about how to differentiate between these options, I typically advise students to think about them as having different overall audiences. 

A *Master's Project* is typically targeted towards an audience composed of practitioners and the general public, and typically demonstrated skills and approaches most closely associated with professional practice. Therefore, a project typically involves some form of substantial engagement with a policy question or domain associated with practice, and might include substantial engagement and collaboration with other practitioners, community organizations, or the public. A Master's project can be initiated and completed as an individual or in groups of several students. A Master's project is written in plain and accessible language, typically contains highly polished visual elements, and oftentimes has a structure that follows that of a plan, policy report, or policy white paper. At UIUC, the final project defense is the presentation of the capstone poster, which happens at our capstone reception every spring.

A *Master's Thesis* is typically targeted towards an audience consisting of researchers and academics, and typically involves major conceptual or empirical investigation of one or more research questions. While much of the structure of a thesis remains up to the author, the format of a thesis is typically prescribed by guidelines produced by the university's Graduate College, and this format must be reviewed and certified prior to submission. A Thesis must be supervised by a committee of at least two faculty, and a formal thesis defense must be held which is open to the public. In our department, students must complete a formal thesis defense and must also prepare and pin up a poster describing their thesis at our capstone reception every spring.

## Which Should I Choose?

I often have students ask me to help them determine which option might be most appropriate for them. It's complicated! The majority of MUP students (probably 95 percent) choose to complete the capstone project option, leaving the other 5 percent to choose the thesis option. Why? In general, it's because the majority of MUP students' capstones track from professional work that they started through internships, class projects, workshops, or other engagements with practice. The flexibility of the project option also means that some students will complete projects more oriented towards academic research as a project instead of a thesis. 

Other students may be interested in a thesis for a variety of reasons. For those students who are contemplating careers in advanced research or who are considering doctoral-level study, completing a thesis can be a good opportunity to try on advanced research. Likewise, student may have existing research interests or engagements that they wish to expand up by completing a thesis.

One thing to keep in mind for research- and "Ph.D.-curious" students is that you *do not* - let me repeat that - *do not* - have to pursue the thesis option in order to successfully apply to research jobs or doctoral programs. 

When I was a Master's student, I completed a capstone project - a [comprehensive plan](https://doi.org/10.17077/svt3-e0ew) written collaboratively with three other Master's students, and then successfully gained entry into multiple Ph.D. programs and pursued further training and a career as a researcher. Likewise, an employer will likely not think much differently about potentially hiring someone who completed a thesis versus someone who completed a capstone (unless the thesis perfectly dovetails with a particular research project or approach the employer is focused on).

This makes the decision more about your desired experience. In general, the capstone takes *more time and effort than you anticipate*. A project takes a lot of time, particularly in terms of the process of professional engagement that's typically involved. A thesis takes *a lot* of time, particularly in terms of conceptualization, getting research approvals (IRB), data collection, and analysis. Students tend to grossly underestimate the time it will take, and fail to front-load the work into the summer and fall of their second year. This can create major challenges during the spring semester when you're trying to finish classes and initiate a job search. For thesis writers, it is more common that ultimately the thesis will not be complete at the end of the second year, meaning that you may not be ready to defend and graduate until the summer term.

This time aspect is important to keep in mind, particularly as you look at the structure of your summer and second year of study, as well as your professional and personal lives. It can be hard to envision what your spring will look like or what parameters will be important as you increasingly spend time on your job search or preparing for further education, but envisioning this can be useful for setting your time. Keep in mind that the capstone is only part of what helps you substantiate your professional expertise and values - you should also invest your time in networking, develop a portfolio of your work, and rehearse a narrative about your professional goals, values, and journey.

## Your Capstone Proposal
Our department requires you to complete a short capstone proposal at the beginning of your second year in the program. Nominally, this two page proposal requires you to supply the following:

1. Project Title
2. Your name (or names if a group project)
3. Description of project and client
4. Detailed work plan with major deadlines
5. Division of labor (for team projects)
6. Outline of end product
7. Description of how the project relates to professional goals
8. For joint degree students, a description of how the project integrates both disciplines.

### Investing in your proposal

It only takes 30 minutes or so to respond to the prompts and write a 2-page proposal. To write a *useful* 2-page proposal will take substantially more time and thought. Much of that time and thought isn't actually associated with writing - it's associated with developing a strong conceptual and practical basis for your work. I strongly suggest that you invest time during the summer in between your first and second years to reflect and draft your capstone proposal. If you're planning to complete a thesis, have a draft ready for your capstone advisor *at the very beginning of the summer* so that they can respond and you can strategically use some of the unstructured time during the summer to invest in your work. While your project will (should) continue to evolve, having a strong starting point will pay off, and will allow you to focus on making more manageable decisions about details.

Here's a few pointers for ways you can invest in your proposal:

#### Description of Project and Client

For a *master's project*, your description will typically focus on a problem statement, policy issue, or describing a process you will develop or implement. The basics are easy, for example:

>Working in partnership with the Busytown office of planning and development, I will draft a revised zoning ordinance, focused on increasing housing density and reducing the reliance on zoning that is exclusively single-family nature.

That's a good start - we know who you're working with, what the output will be, and what it's focused on. Don't stop there, though. Provide background so we understand *why* these policy changes are needed now.

>Busytown's city council has closely followed ongoing national debates regarding the elimination of single-family zoning. While the city council maintains the position that some single-family zoning should remain, they have asked the planning department to identify criteria for which neighborhoods currently zoned single family might be most appropriate to allow multifamily uses, and have also set a goal of upzoning zones to allow higher-intensity multifamily land uses. The city's zoning ordinance last received a major update in 1998. In 2019, the city initiated a land use analysis designed to inform zoning reform, however, the COVID-19 pandemic forced planning staff to put this analysis on hold. Part of my work will involve collaborating with city staff to resume and complete the process initiated in 2019, and I will then translate findings from this analysis into a series of proposed revisions to the city's zoning ordinance.

For a *thesis* you'll want to use this section to talk more generally about your project:

> My thesis examines how climate change alters the financial landscape associated with owner-occupied housing in Houston, Texas. Much of our recent understanding of the evolution of financial risk in homeownership has focused on consumer finance and access to capital in the wake of the Great Recession. I focus instead on the evolving landscape of risk associated with homeowner's insurance in coastal regions of the U.S. that are directly impacted by sea level rise. Drawing from a series of interviews with insurance industry professionals, real estate professionals, and local government officials, I question whether the risk-based pricing model is sustainable within these contexts. I also identify which populations are likely to be most disparately impacted by changes in risk practices.

Essentially this description should serve as an abstract for your thesis. Just like the project description, you should cover the who, what, where, why, and how of your thesis. For a thesis, you may want to think about attaching your overall thesis proposal (which should be longer than two pages). If you have taken my advice and prepared in advance, you'll already have a thesis proposal and abstract which can be utilized for filing your capstone proposal. Note (at least for my advisees) that I expect a separate and more detailed thesis proposal (typically 4-6 pages) drafted and discussed over the summer between years 1 and 2.

#### Detailed Work Plan with Major Deadlines
We now have a pretty clear picture of the what, where, and why of your project, as well as the expected outcomes. Now is time to break these outcomes into distinct work products. These distinct work products may be structured around particular subtasks you've identified, the structure of your writing, or by external factors and resources (such as a client's timeline or when they plan to hold public meetings). Regardless of what factors are imposing structure on your project, the work plan offers an opportunity to define distinct phases of the project. I suggest using these distinct phases as opportunities to solicit feedback from both your client and your advisor.

Thinking about the hypothetical Busytown project, I see three distinct phases:

**Phase 1:** Update and complete land use study.

**Phase 2:** Develop initial proposal for amendments to the zoning code.

**Phase 3:** Develop staff report outlining finalized recommendations for amendments to the zoning code.

Identifying phases is useful for breaking the project into manageable chunks. The next challenge is to establish a timeline associated with each of these chunks. I will repeat something I've said before - students tend to underestimate the amount of time tasks will take, and often fail to front-load time-intensive tasks into the fall semester to allow more time for writing, analysis, and polishing in the spring. You should keep this in mind and use it to help you develop your realistic plan.

I typically encourage students to use department and graduate college deadlines to work backwards through their timeline. It is a grave mistake to look at your capstone schedule and simply work backwards from the end of the spring semester. Instead, you should be working back from the department deadline when your draft is due to your adviser. If that date hasn't been published yet by the department, I suggest to my advisees that you use the end of Spring Break as your deadline to have a complete draft of your capstone. Spring break is a lot earlier than the end of the semester!

For thesis students, you will want to work backwards from the Graduate College's deposit deadline for complete theses. You need to schedule your thesis defense well in advance of this deposit deadline, so that you have sufficient time to incorporate feedback received during your defense into your thesis manuscript. In some cases, your committee may make approving your thesis contingent upon you making some changes. In some cases, committee members may ask to review these changes prior to the final review by your adviser and your deposit. Consequently, I recommend scheduling a thesis defense 2-3 weeks before the Graduate College deposit deadline *at the latest*. As a courtesy to your committee, you should plan to share your completed thesis manuscript 2 weeks before your defense so they have sufficient time to review. It's also important to work with your adviser to schedule a defense date early so that you can reserve the time on your committee members' calendars and so the department can make a public announcement about your defense.

#### Outline of End Product

I've seen students complete this in two ways - one, literally providing an outline that lists major sections in their planned document; and 2, a narrative description of what the end product is. As an adviser, the narrative description is far more useful for accountability and advice giving.

In the case of our Busytown land use example, I see several discrete end products that will be incorporated into the capstone:

1. Land use analysis
2. Staff report containing proposed revisions to the zoning code
3. Capstone poster

Items 1 and 2 are discrete deliverables that will be delivered to the Busytown planning staff. The student completing this work will combine the substantive elements from these two documents to create the master's project. They will also submit a poster that summarizes and presents their work to a public audience.

For a student writing a thesis, it might be tempting to throw a stock research paper outline in this section and call it good:

1. Abstract
2. Introduction
3. Literature Review
4. Research Questions
5. Methodology
6. Results
7. Discussion
8. Conclusion

Again, this is not too useful for providing advice or creating general accountability, especially during the early thesis stages where this is particularly important. This is a good time to talk about the main types of evidence and analysis you will use and how this evidence and analysis makes a contribution to our knowledge. For example...

> This thesis draws on a series of interviews conducted with insurance industry professionals, real estate industry professionals, and local government officials in Houston, Texas. I plan to conduct approximately 20 interviews with stakeholders in the Houston metropolitan area. Because of the size of the region, and unevenness in the region's exposure to risk related to climate change, I use FEMA flood maps and data on recent flooding events to identify where spatial unevenness exists. I then use this information to inform my selection of stakeholders, particularly local government officials and real estate professionals, who are likely to be more bound to working in housing markets with particular risks associated with them.

> This approach is novel in that it brings together the voices of industry professionals who are ultiamtely determining how risk is expressed and managed through insurance products. It is also novel in its attempt to explore spatial unevenness in risk patterns by taking a spatially-informed approach to sampling.

> This work is important for scholars in the housing policy and natural disaster community, as well as for local and national policymakers concerned with housing affordability, housing stability, and climate change. In addition to the complete thesis manuscript, I intend to work with my adviser to develop an initial manuscript from this work suitable for publication in a scholarly journal like *Journal of the American Planning Association* or *Housing Policy Debate*.

The whole point here is to help us see where you're going and what your goals are for how people will make use of the insights and contributions from your work.

#### Relationship to Professional Goals

We ask this question because it's important for us to see how your capstone fits into your professional goals. This is part of the narrative setting that will ultimately help you get a job or write a convincing statement for further graduate study.

It's important to understand that we don't expect you to know exactly what that next step is, but by the point you're writing this narrative, you should have some sense of the professional capacities and identity you wish to lay claim to when you complete your graduate degree. The more detail you can start to flesh out here, the better the advice and resources your advisor and other program staff can help you with during your second year of study.

## Concluding Thoughts

This is a lot of information, however, I hope that you find it useful in helping to frame your work. As I've hope I have been able to make clear, the formal proposal paperwork shouldn't be seen as the beginning of your project or thesis - it is more like a distinct moment when you describe the basic elements of your project and commit to the foundational principles of your project. The project will continue to evolve as you work and as you receive feedback from your adviser, and from the act of doing the work itself.

As I've mentioned several times, this part of the Master's degree is really bespoke to you and your relationship with your adviser. Talk with them early to develop a plan. Ask questions to help flesh out their expectations and to establish shared expectations for your work. Think carefully about how to fully account for the time and effort cost of completing your capstone - and protect this time as you make other personal and professional commitments.

From my perspective as an adviser, the capstone is one of the most fun and interesting ways I get to interact with students and engage with a variety of questions and topics through their work. If we're working together, I look forward to our collaboration and to many conversations about your work!