---
title: "Ph.D. Milestones"
format:
  html:
    page-layout: full
    toc: true
    toc-depth: 4
sidebar: true
---

This documentation is designed to help my advisees and students in the Regional Planning Ph.D. program at University of Illinois at Urbana-Champaign to navigate major Ph.D. program milestones. It is likely that while some of this information may be somewhat specific to this program, that individuals in other graduate programs, particularly those in other urban planning doctoral programs may find this information useful and transferable.

The usual caveats apply, however - your mileage may vary, and these are my personal opinions and should not be taken as those of my employer or as policy associated with my roles in the department and university.

## Ph.D. Program Structure

Although by their nature they are diverse, most Ph.D. programs in the United States follow a similar structure. I like to think of the Ph.D. as having three main stages:

1.  Coursework
2.  Advancing to Candidacy
3.  Dissertation

There are different mechanics to each of these three phases which make them distinct from each other. Over the course of these three phases, you are expected to build expertise and an identity in a particular area of focus; situate your identity within the work which others have done in the past, test and affirm your general area of expertise and unique positionality, and then further demonstrate your capacity to design and execute original research related to your expertise (it's just that simple!).

Let's break down the mechanics of these three phases.

### Coursework

Most U.S. Ph.D. programs require a few years of coursework. In the case of the Regional Planning Ph.D., we require students to complete the equivalent of four semesters of coursework during the first two years of study. The value of this period is that is provides a structured framework for building knowledge related to your area of expertise (and general conceptual and methodological knowledge necessary for research).

For any Ph.D. student, taking classes is not at all a new endeavor. At the same time, I think many Ph.D. students struggle during this phase to sufficiently define their academic identity in a way that will allow them to efficiently advance to candidacy (the next phase). The structure and rhythm of taking classes masks for some Ph.D. students the other tasks that should be going on during this period - broad and deep reading and conceptualization of literatures, and the development of an individual positionality situated within relevant ones.

#### Developing Your Reading Practice

There is no substitute for building exposure to a wide breadth of literature by reading it. Classes are one place this will happen, but sustained engagement with literature outside of class is also important. The implications of reading wide are that it is inherently inefficient, particularly towards the beginning of your doctoral studies. At the same time, there's substantial benefit to the exposure you receive to others' scholarly work, even if you ultimately don't find it relevant to your own - reading widely helps you develop a sense of what you identify with or include as part of your domain of expertise, and also helps you articulate what you exclude or place outside of that expertise.

I encourage my advisees to develop a *daily reading practice* starting early in their time in the program. This is a daily allotment of time to read work outside of what you're reading for classes. When I was a an early Ph.D. student, my daily reading practice typically involved 3-4 hours at a coffee shop 4 days a week. Yes, that's a lot of time, but it's also a privilege to be able to invest your time in your own knowledge formation and development. Your mileage (and writing practice) may vary - you have to figure out the time, pace, and structure that works well for you, that is constructive for your scholarly formation, and that fits into your life and other obligations.

I suggest that your daily writing practice build out from a range of initial cues. This may at times start with assigned readings from coursework, or may include readings you select independently from your classes just because something about them interests you. Oftentimes the implications of reading broadly are that you might start with a key text and then pick up reading some of the main works that the author cites in their own argument. You might keep building out from there (within reason) to start to understand how scholarship builds and compounds on the scholarship of others. It may also be useful to get "referrals" for key texts from your adviser and other faculty, and from student colleagues in your department or other departments. The key principle here is that this process of reading should be intense but also fun!

Again, the goal during this stage is to start to *play with your own ideas* and the ideas of others to help refine the key questions that drive your work and to start to identify domains of expertise that you lay claim to (more on this in our conversation on the qualifying phase).

#### Using Classes Strategically

Your first two years of study will typically also consist of coursework - some of this will be courses required for Ph.D. students in your program, but you are likely to have a substantial amount of flexibility regarding your course selections. In addition to these core areas of baseline domain knowledge, your course strategy will likely see you hone your domain knowledge with regards to theory related to your areas of focus, knowledge of research methods, and may include other domain-specific knowledge related to specific applications of knowledge (in planning, these are often courses focused on specific policy domains or practices). You will likely also take graduate-level courses alongside Master's students in your program and other programs.

In general, the key to coursework is to have a clear goal or concept for how each course will help to advance your work. In some cases, you will take a course for substantive content - methods, theory, etc. The goal for these course may simply be to learn content or approaches that are new to you. Other courses you may have a different goal - expanding domain-specific knowledge, for instance. Oftentimes, for these types of courses, it may be useful to think about an application of that knowledge that allows you to bridge or interface with your own discipline or area of study. Faculty may be open to allowing Ph.D. students to pursue term papers or projects in lieu of some assignments - this can be a great opportunity to use a course to advance your own goals and agenda by working on your research and scholarly identity through the class.

It is also useful to keep your ear to the ground for specialized seminars offered during your coursework phase. Oftentimes these may be special topics or courses offered only for Ph.D. students in a specific discipline. Oftentimes these courses can offer specialized knowledge, intensive engagement, and the opportunity to build connections with Ph.D. students in other fields. These are valuable opportunities not only to expand your repertoire, but also to learn how to "do the discourse" and participate in dynamic conversations.

#### Key Takeaways

Here's the key takeaways for your coursework phase:

1.  Have a Plan and Narrative: You will have a lot of flexibility in what you take - you need to come in with a concept for how you will structure your Ph.D. coursework to build core theoretical, methodological, and domain skills. On top of that, you need to develop a narrative that interweaves the choices you've made into how you frame your identity as a Ph.D. candidate (more below).

2.  Courses Serve Multiple Purposes: As you write and think during your coursework period, use coursework as an opportunity not just to think but also produce writing that advances your ideas. Some of this writing (and related research) should be good substrate for conference papers and can be worked into peer-reviewed papers.

3.  Embrace Being a Professional Student: Your engagement during the coursework phase isn't just in the classroom - you need to also develop a reading practice to build breadth and depth of knowledge, and will likely also gain experience as a Research Assistant or Teaching Assistant, learning elements of the trade. Immersing yourself in learning across these contexts is important, and is also your full-time job.

#### What Advisors Want to See

As a Ph.D. adviser, the main thing I want to see my advisees do during the coursework phase is to immerse themselves in the process of fleshing out their academic identity and practice. I want to see evidence that my advisees are reading widely and grappling with new ideas. I also want to see that they are pushing themselves in their coursework to develop outputs that reflect their evolving thinking.

### Advancing to Candidacy

Advancing to candidacy is when things start to get real. The candidacy phase essentially marks your transition from being a knowledge consumer to being a knowledge producer. Advancing to candidacy requires the completion of your qualifying exam and completion of your dissertation proposal defense.

Of all the phases of the Ph.D., I think that advancing to candidacy is often the least well-defined stage and also the one that causes the most intimidation and anxiety for doctoral students. This is also a time period where many students have a tendency to lose momentum or drag their feet due to the transition from the externally imposed structure of coursework to a period during which the student must define and impost their own structure.

During this period, which should ideally be only a few months long, you must articulate a coherent academic identity including domains of knowledge and related literatures which you claim expertise in, be tested on your command of your identity and its constituent domains, and articulate how you will apply your unique identity to a particular research project (the dissertation). Let's break down key considerations for each phase.

#### Qualifying Documents

Most departments ask doctoral students to produce a set of qualifying documents. These may include a plan of study in which you articulate your academic identity and history, a bibliography or similar document in which you identify domains and constituent literatures that are most relevant to your academic identity, or some other form of representative writing or research that demonstrates your positionality and identity.

You should be making investments in your qualifying documents starting on day one of your Ph.D.. This may include early versions of your plan of study in which you begin to outline your identity and research, and may also include growing your bibliography as you read widely and eventually deeply. The writing you do during the coursework period may also inform statements of your academic identity and your positionality as a researcher.

As an adviser, my goal is for students to independently develop and share these pre-qualifying documents while they are still taking coursework - this allows me to think about both timing for exams and to start to develop my own vision for what their examining committee might look like. As an adviser, I will never dictate an examining committee, but I may be opinionated in providing suggestions for committee members.

#### The Qualifying Exam

Talking with Ph.D. students, I think the qualifying exam may be more anxiety-producing than the dissertation process. Arguably, the notion of an exam does convey that the stakes are high, and there are real consequences for failing the exam. In general, an adviser will not let a student take the exam until they are confident they will pass it. I encourage my students to think about the qualifying exam as a unique moment to show off their identity and approach as a scholar. This is a reflective moment that should be confidence-building.

Essentially, we're testing your knowledge and application of the domains you claim expertise of in your pre-qualifying documents. We use your pre-qualifying documents to craft questions that will ask you to demonstrate your command of theory, methods, research design, and domain-specific knowledge. Typically, your committee members will each take the lead on at least one of the questions, and may design some working together. Even if committee members take the lead on designing a question, all committee members will read and be prepared to comment on your responses during your oral defense.

Different programs will have different exam formats. I am most accustomed to an exam format that is a period of writing and responding to questions from the examining committee that lasts around 1 week. I have heard of some institutions structuring exams to last hours or to be conducted in a timed fashion in a classroom. I typically design exams to be completed off campus (or wherever the student wants), with no time limit for individual questions, and an overall examination window of 7 days. Exams can be open book or closed book, but I tend to prefer open book exams because I can then see how a student leverages their command of literature.

Typically you will need to provide an oral defense of your responses. When I took my exams, I envisioned a tribunal in which a wrong response might send me to the academic gallows. The reality is that the oral is typically a highly constructive and supportive process. Oftentimes, the oral defense will also be an occasion where your examination committee might share some thoughts about the implications of your thoughts for a potential dissertation framework and proposal. Again, the goal here is that this is a unique moment of constructive feedback. Of course if there are serious concerns about an exam response, you may be asked to provide more detail and accountability, or to re-approach the question with some additional writing.

#### Dissertation Proposal

The final stage of advancing to candidacy is the successful defense of the dissertation proposal. Since the dissertation proposal is highly contextualized by the dissertation process, let's talk about it in it's own section below.

### Dissertation

Now that you have completed your exams, it's dissertation time! This dissertation feels like (and is) a big thing - a major research project and manuscript taking a deep dive into a specific research question. While this can appear daunting, you have the support of your adviser and committee who should be providing feedback and guidance along the way.

#### Developing a Proposal

This is not a linear process. In most cases, you should have started developing a dissertation research concept during the time when you were taking classes. Oftentimes, the dissertation conversation will also happen alongside your exams, and your exam committee should be thinking about how their reading of your responses might also inform or contribute to your dissertation. In many cases, students have also begun field work or preliminary research prior to defending their proposal.

These things are all okay - again, this is not a perfectly linear process. The key though is that the examination process and the dissertation proposal should be intertwined, which means your examination prep is also dissertation proposal preparation. This is the mindset that I think helps students approach the candidacy phase most effectively and efficiently.

Ultimately, your proposal needs to be extensive enough that your committee can clearly see the context and rationale for the questions you seek to engage, appropriate methods for engaging them, and an appropriate plan for analysis and communication of your results. The more details and information you can provide, the better feedback your committee can offer. Keep in mind that even dissertation proposals that appear iron-clad and extensive are going to be challenged by the natural uncertainties that occur within big and complex research projects. The dissertation proposal is a good faith effort to flesh out a research concept and plan that *is going to change* but that changes in ways that are consistent with your original proposal.

Different advisers and committees will have their own standards for what a proposal should contain. At this point in your academic career, you should be able to conceive of what a proposal would need to contain without needing the guidance of your adviser or others to offer a template. It may be useful to take a look at others' proposals, but remember that each of these is unique and yours should be unique and consistent with your approach too.

At a minimum, you will need to provide a context and rationale for the project, clear research questions, a clear and rigorous description and justification for your research approach, a clear sense of how you will analyze your data and what key outputs or kinds of insights will result as you answer the questions you have developed. Again, details matter here, so you should be thinking about what details you will a) need feedback on, and b) your committee will expect to see from you to feel confident that you know what you're doing.

#### Working with a Committee

Most dissertation committees consist of several members of the faculty in your department and at least one faculty member from another department on campus or at another university. You will select your committee members based upon the contribution of their expertise towards your overall research project. In most cases, members of your exam committee will also serve on your dissertation committee - learning and feedback process from the exam is a great way for your committee to develop familiarity with your broader intellectual project and an understanding of how the specific work you do in your dissertation fits into the context of your broader scholarly identity and approach.

In addition to thinking about the contribution of subject matter expertise, it can also be useful to think about how certain committee members may be able to connect you to scholarly communities and networks during and after the conclusion of the dissertation process. It would be disingenuous to invite committee members based upon their network alone, but connection to networks can be an important form of support.

It is also important to think about the specific role which committee members might play during the dissertation process. Your adviser's job is clear - they are your academic sherpa and helping you to manage the entire process. Next to yourself, they are accountable in making sure you are progressing and have adequate support. They are oftentimes the responsible party (PI) on your IRB. You are likely going to rely upon the subject-area knowledge of other committee members. It can be useful to have an intentional conversation with committee members about the role you want them to play. Yes, they will ultimately read and comment on your whole dissertation, but you may also ask committee members to focus on particular aspects of your work - methods, theory, implications for practice, etc. There's no right time to assign or delegate such roles, but it is often useful to do so around the time you start writing and have chapters or draft materials to share.

#### Transitioning to Candidacy

Once you complete your examination and dissertation proposal defense, you have completed the transition from a doctoral student to a doctoral candidate.

This transition is an exciting one, but also a dangerous one. After you complete your exams and proposal defense, you will likely be feeling a sense of both accomplishment and also exhaustion, and you'll also be dealing with the transition I mentioned before from the relative structure of knowledge consumption to the more open-ended structure of knowledge production.

The key here is to not allow yourself to be caught in an academic doldrums. You will have to dig deep to keep moving forward, but it will be worth it!

#### Research and Writing

It's off to the races! In reality as I've mentioned before you have likely already begun aspects of your dissertation research before you defended your proposal. You may have already sought IRB approval for aspects of your proposed research. You may need to submit an IRB protocol for review or amend an existing protocol to reflect new aspects of your project.

This is a hard phase to encapsulate because it will look different based upon your research design, methods, and strategy. The key here is to understand that very few dissertation projects turn out exactly as conceived of in the proposal. When you defend your dissertation, dissertation committees tend not to be looking for absolute fidelity to what was in your proposal, but will be looking at how you have evolved your research project to meet the overall goals you set out.

It's also important to understand that the dissertation research phase is simultaneously exciting and a very isolating experience. Your expertise in your specific research project eclipses that of your adviser and committee (not that they don't have strong opinions about components of what you're doing!).

In addition to the support provided by your committee, it is important to develop practices of support for yourself during this period. As with the research side of things, its hard to give more specific advice regarding what that support may look like. This is a great time to build a balanced routine focused on your work but also on bringing your personal needs into focus. Taking care of your mind, body, and social needs are important alongside advancing your research and other professional needs.

Depending upon your financial arrangement, you may either be on fellowship during your dissertation or working. Working alongside conducting your dissertation research can feel like a lot, but at times it can be productive exposure to what life will be like if you choose to pursue employment as a professor. Fellowship can be an excellent way to make substantial advances on your research, but make sure that you are also keeping your other professional goals and needs in focus.

#### Committee Feedback

As you're writing you should also be seeking out feedback from your committee members. As mentioned earlier, you may identify different areas which you ask committee members to focus on given their academic background. Some committee members you may choose to engage more and others only selectively. You have to develop a strategy in consultation with your adviser that will work for you and that also respects your committee members' time.

At the same time, it is valuable to regularly seek advice from your committee members and to have their eyes on your work once you have complete chapters, papers, or analyses to share. This can help to address issues that are otherwise likely to come up during your defense.

#### The Defense

Congratulations! You made it to the point where you have produced a manuscript, received feedback, and are prepared to defend your work.

Like the qualifying exam, the dissertation defense can seem like a scary (or at least vulnerable) milestone. The defense is designed to do four things:

1.  The defense is an opportunity for your committee to review your work, provide feedback, and help you make changes to polish your description of what you've done and why it's important.

2.  The defense is an opportunity for public celebration of your accomplishments.

3.  The defense ts an opportunity for your committee to review and certify that you have demonstrated the capacity for rigorous independent research.

4.  The defense is a final formal occasion for your committee to provide feedback that looks at your next steps after you deposit your dissertation and prepare to graduate.

A typical defense (at least in my department) will be scheduled for two hours and will consist of both a public component and a private component. When I am running a defense as an adviser, I typically expect that we will do the following:

1.  **Pre-Defense Conversation** (a week before the defense) - I will have a conversation with my advisee to talk about the structure and format of the defense and I may provide advice on what types of questions to anticipate from committee members. My advisee might share a draft version of their defense presentation and I will share feedback (typically, I request cuts to the number of slides included in the presentation). I will also typically reach out to each committee member before the defense to see if they have any major questions or concerns that we should talk about before the defense.

2.  **Introduction** - At the beginning of the defense, I will take a moment to say a few words about the work which my student has done and about their background. I will also allow each of the committee members to introduce themselves.

3.  **Research Presentation** - now the floor is yours - at this point, my student will give a 20-25 minute presentation describing their dissertation research. This will cover the research rationale, background and literature, approach, results, and discussion of findings.

4.  **Community Questions** - I like to invite any members of the public present at the defense to ask questions they may have before I invite committee members to comment. It is often intimidating for guests to interject once committee members have started their comments. In general, most guests present haven't read your manuscript, so their questions will be based upon the narrative you provide during your research presentation. Typically these are pretty light and easy to answer (unless a friend or family member really wants to grill you on something). As an aside, this is a public celebration, so you should feel welcome to invite friends and family. Increasingly, we accommodate friends and family joining via Zoom, which is also a nice way to invite people in to the special moment.

5.  **Committee Questions** - After guests at your defense have the chance to ask questions, I will invite committee members to ask questions. At this point, you should be able to anticipate what types of questions each of your committee members might ask, based upon your past conversations and interactions around your dissertation. Again, assuming there aren't major holes in your dissertation research, these questions are usually more friendly than you might anticipate - the goal during your defense isn't to grill you, but rather to support and celebrate your work and accomplishments, and to develop evidence for the advice the committee will give you in private conversation.

6.  **Committee Conversation** - After your committee members have asked all their questions and you have responded to them we will conclude the public portion of your defense. Guests will be asked to leave, and the doctoral candidate will also step out momentarily. The committee will then talk about defense results and guidance. There's two main questions on the table at this point - one, what are the results of the defense (pass, pass with revisions, fail); and, two, what feedback or guidance does the committee want to provide regarding how to finalize the dissertation. With regards to the overall exam results, the decision between pass and pass with revisions typically revolves around the extent of required revisions, and how comfortable the committee feels with allowing revisions to happen without further committee review. Typically an adviser would not allow you to schedule an exam if they saw an imminent risk of the result being fail (it would be cancelled and rescheduled after issues were addressed).

7.  **Results** - after you have the chance to sweat for a while and the committee completes their deliberation and assembles their overall advice, the doctoral candidate will be invited back into the examination room to receive the results of their defense examination. Again, typically this will come in two parts - first (hopefully) a hearty congratulation followed by a summary of advice and feedback on the dissertation. Depending upon the nature of the advice and the extent of changes called for by the committee, they may decide that the student and adviser can handle them without further committee review, a particular committee member with a concern or question may request additional review around a component in question, or the whole committee may wish to review again before making a final determination on the dissertation.

#### Post Defense

Breathe! From the outside, it often looks like the defense is the last hurdle to clear. In reality, the dissertation deposit more accurately is that last hurdle. As you come down from your defense, you will likely have a "punch list" of edits assembled from your committee feedback. At best, these will be minor things (misspellings, add a reference here, look at paragraph framing here). In some cases, there might be more substantial edits - add new framing to chapter X, run an additional validation step and update results in chapter Y. The key here is to budget a realistic amount of time for each of these tasks and then execute them.

Here are some of the common things which I see doctoral candidates having to revise following their defense:

1.  **Methods:** Details matter in methods section, and oftentimes by the time you conclude your dissertation, what you did doesn't quite line up with what you wrote in your methods section.

2.  **Discussion:** Discussions are hard to write, particularly when you have in-depth knowledge and command of your research. I often see students need to do some re-thinking and additional synthesis of their discussion following their defense.

3.  **Conclusion:** Conclusions are even harder to write than discussions! Oftentimes, it is very clear in the defense draft that the author doesn't really know what to say in their conclusion. Oftentimes this can be a good place to intertwine reflections on the research process, the knowledge gained, and the broader implications of the work.

4.  **Font/End Matter:** Students completing a three paper dissertation often struggle to adequately develop their introductory and concluding portions of their dissertation. In particular, students fail to conceptualize how the three papers are interrelated and contribute knowledge addressing a particular overarching research question. Likewise, there's often under conceptualization in the concluding chapter regarding how the results from the three papers can be read together and what their implications are.

The university typically has a deposit deadline by which all individuals looking to receive their degree in that semester must deposit a complete and correctly formatted dissertation manuscript, along with the signed committee result form from the dissertation defense. Typically, you can find such information on the Graduate College calendar.

It is important to keep timing in mind here - even with meticulous attention to detail, it is likely that you will need a week or two to complete final edits and formatting of your dissertation manuscript for deposit. You also want to allow sufficient time for your department and the graduate college thesis reviewer to check and approve your thesis for deposit. It's easy to underestimate (or discount) the time this will take when you are scheduling your defense, so be forewarned and conscientious about this as you plan your deposit.

## Milestones

While the above information should be easily transferable across other planning (and related types of) Ph.D. programs, I also want to provide a few thoughts on our department-specific key milestones.

### First Semester Independent Study

We require Ph.D. students to complete a 4 credit hour independent study with their Ph.D. adviser in their first semester in the Ph.D. program. The goal of this independent study is twofold - first to refine some of the reflections in the Ph.D. Plan of Study which you first drafted during the Graduate Student Orientation; and, second, to begin the process of reading widely to develop the foundation for the annotated bibliographies you will produce as part of the qualifying process. Of course an implicit goal of this process is to start to develop a relationship with the Ph.D. adviser.

Even though most Ph.D. students already have grad school experience coming from their prior Master's degree, it can be difficult to adequately carve out time for this first semester independent study, particularly while taking other classes and adjusting to the Ph.D. student identity. This falls in line with my earlier comments on developing a reading practice.

As I will underscore when talking about the Plan of Study, I encourage my advisees to continually revise and add to their draft Plan of Study document. This should be a *living document* which you evolve and contribute to constantly until your exams.

### Plan of Study Meeting

Our department requires Ph.D. students to complete a Plan of Study meeting with their adviser and one other department faculty member by the end of the second semester in the program. The purpose of this meeting is to provide feedback on the Plan of Study as it stands at the end of the first year in the program.

While your Plan of Study committee will read your document in a holistic way, we're oftentimes looking at the consistency between what you write about your academic identity and goals and what you plan to do during the two years before you advance to candidacy. We will oftentimes give advice on classes, potential faculty in other departments to draw upon as a resource, and will provide substantive feedback on your goals and the framing of your scholarly project.

### Qualifying Exam

I've hopefully provided sufficient thoughts above on the qualifying exam process. Our department requires you to produce two annotated bibliographies with the idea that these bibliographies will inform your qualifying exam. To underscore a point I made in describing the qualifying exam process, these annotated bibliographies require *synthesis* through the lens of your stated academic identity.

To be clear, I ask my advisees to produce or expand upon their statement of scholarly identity in their Plan of Study to help inform how they view and synthesize the literature they lay claim to.

This means that coming into the exam, a student should deliver to their examination committee an updated Plan of Study including an expanded statement of scholarly identity alongside two annotated bibliographies that contain writing that describes and synthesizes the literatures they claim mastery of.

Our department offers two exam options - the Qualifying Written Exam or the Qualifying Paper Exam. I am an ardent proponent of the Qualifying Written Exam as I think it requires you to do additional synthesis associated with your claimed domains of expertise. The Qualifying Paper, by contrast, asks you to demonstrate that you can apply concepts to producing an original empirical or conceptual contribution to academic discourse.

Again, different faculty have different preferences, but I very strongly encourage my advisees to pursue the written exam option.

One other note here, to underscore points made above - you should be thinking carefully when you assemble your exam committee. In most cases, your committee consists of department faculty, and these individuals will likely continue on to serve on your dissertation committee (although aside from your adviser, there's not a requirement that your dissertation committee has the same members as your exam committee). In most cases, the benefit of having departmental faculty serve on both your exam and dissertation committee are that the exam gives them a broader context for understanding the specific application of your scholarly identity (and prowess) to a particular narrow research question - the dissertation.

As I mentioned earlier, regardless of which examination option you choose, your oral defense will likely include some time workshopping how you will transfer knowledge and conceptualization from your exams into a dissertation research proposal and project.

### Dissertation Proposal Defense

Again, I think I've (exhaustively) described the dissertation proposal defense process. One thing to keep in mind is that our department requires at least one dissertation committee member to be external to the department. This could be a faculty member in a different department on campus, or a faculty member at a different university. You will identify who this external committee member is through several careful conversations with your adviser.

### Dissertation Defense

This is a big milestone, but the dissertation defense is pretty universal, so I don't have much to say here beyond what I said previously above. In my experience, the dissertation defense format and expectations are fairly uniform between degree programs and departments. My suggestion to my advisees is always to go to as many dissertation defenses in our department as possible. They're useful and help to clarify a lot about the process.

## Concluding Thoughts

These thoughts got a lot longer than I anticipated they would! I have tried to encapsulate some of the advice that I find myself repeating to students over their time in the program. Of course, these are my opinions and view points, and don't necessarily reflect the specific policies of my department or university.

Having been a doctoral student (now a shockingly long time ago), I know the phases and milestones associated with a Ph.D. can be unclear, mysterious, and intimidating. At the same time, I think it's very important to have the big picture of the Ph.D. phases and milestones in mind, as well as some thoughts on what the explicit and implicit goals of these are.

The Ph.D. is not a linear process - sometimes that can be a beautiful thing, and sometimes it can be extremely frustrating! At the same time, the process should be fun (in the balance). Hopefully this perspective helps you to chart our your own course and enjoy the nuances of each phase just a little more than you anticipated!
