---
title: "Classes"
format:
  html:
    page-layout: full
    toc: true
sidebar: false
---

## Spring 2026

### UP 510: Plan Making Workshop

Workshop Description: Central Illinois’ housing landscape is rapidly changing due to major changes in population as well as major changes in both state and federal housing policy. Many communities throughout the region lack the capacity to strategically understand local housing needs or to think systematically about how local needs fit into the broader regional housing landscape. To engage these issues, in this workshop we will conduct a regional housing needs assessment with the goal of both describing the evolving housing landscape present throughout central Illinois and then providing guidance on potential strategies to address identified needs.

Over the course of this workshop, we will work with the Central Illinois Land Bank Authority and other housing agencies in central Illinois to analyze trends related to housing supply and demand, and to develop a broader understanding of institutional needs and goals related to housing. Students in this workshop will work with public and proprietary sources of housing and community demographic information to produce a regional picture of housing needs, and will also gain experience conducting interviews and facilitating conversations with local communities and institutions about housing and community change.

Expected Outputs: Outputs from this workshop will include a polished professional report summarizing the process and findings from the needs assessment. As part of this needs assessment, secondary outputs will include a data dashboard for sharing information with local communities as well as an intervention toolkit that describes potential intervention strategies to address needs that are identified.

### UP 591: Capstone Seminar

[Course Website](https://up5912526.netlify.app)

**All MUP 2 students should register for 0 credit hours.**

The MUP Capstone Seminar is designed to structure and support the early stages of the 2-semester capstone sequence. Over the course of the seminar, students will structure their capstone project or thesis, develop a work plan, and develop a timeline and accountability strategy. By the end of the first semester workshop, students will complete project background work and develop a clear strategy for project completion and dissemination in the second semester. All MUP 2 students take 0 credit hours of workshop in the spring.

### UP 592: Doctoral Urban Planning Seminar

Year 1 and 2 Ph.D. students should register for 0 credit hours.

The Doctoral Urban Planning seminar is a platform for intellectual development for PhD students in the Department of Urban & Regional Planning and a medium for building a community of scholars. The seminars facilitate the exchange of ideas and perspectives among urban planning Ph.D. students and faculty. The seminar is intended to benefit doctoral students across all stages in their research and doctoral studies, and provides a shared space for students to present their research and to solicit critical, yet constructive, peer reviews and advice.

## Fall 2025

### UP 473: Housing and Urban Policy

[Registration Link](https://courses.illinois.edu/schedule/2025/fall/UP/473)

Housing represents a fundamental human need and a critical element of human settlements. Within the context of urban planning, housing represents one of the ways in which planning intervention has sought to ensure the health and safety of residents, while also bearing influence on the spatial, social, and economic relationships that differentiate housing and other land uses. Within this class, we will explore the policies and practices that constitute housing policy in the United States and abroad, in order to understand where and how planning strategies have been effective (and ineffective) at shaping physical, economic, social, and political dimensions of housing.

By the end of this course, we will develop:

1.  An understanding of the housing production and regulation system in the United States;
2.  An understanding of historic and contemporary housing policy intervention strategies;
3.  An understanding the intersection between housing policy and other urban policy initiatives;
4.  A framework for evaluation and analysis of housing policies in the US and abroad;
5.  Strategies for effective analysis and communication of housing policy trends and impacts.

### UP 591: Capstone Seminar

[Registration Link](https://courses.illinois.edu/schedule/2025/fall/UP/591)

[Course Website](https://up5912526.netlify.app)

All MUP 2 students should register for 0 credit hours.

The MUP Capstone Seminar is designed to structure and support the early stages of the 2-semester capstone sequence. Over the course of the seminar, students will structure their capstone project or thesis, develop a work plan, and develop a timeline and accountability strategy. By the end of the first semester workshop, students will complete project background work and develop a clear strategy for project completion and dissemination in the second semester. All MUP 2 students take 0 credit hours of workshop in the spring.

### UP 592: Doctoral Urban Planning Seminar

[Registration Link](https://courses.illinois.edu/schedule/2025/fall/UP/592)

Year 1 and 2 Ph.D. students should register for 0 credit hours.

The Doctoral Urban Planning seminar is a platform for intellectual development for PhD students in the Department of Urban & Regional Planning and a medium for building a community of scholars. The seminars facilitate the exchange of ideas and perspectives among urban planning Ph.D. students and faculty. The seminar is intended to benefit doctoral students across all stages in their research and doctoral studies, and provides a shared space for students to present their research and to solicit critical, yet constructive, peer reviews and advice.

### UP 597: Planning for the Silver Tsunami: Alternatives for an Aging Society

[Registration Link](https://courses.illinois.edu/schedule/2025/fall/UP/597) (Independent Study. CRN: 59267, Credit Hours: 4)

[Course Website](https://up597f25.netlify.app)

In the United States, overall life expectancy has increased dramatically from 69.8 years in 1960 to 78.4 years in 2023 per the Centers for Disease Control and Prevention. While this represents an increase of over 12 percent, it lags behind the gains seen in other developed nations (e.g., the United Kingdom). Although these estimates are moderated by sex, race, and ethnicity within the U.S. with lower life expectancy for males and individuals of American Indian and Alaska Native or Black single race groups, the trend toward greater longevity is clear. This independent study course explores the implications of an aging population for local governments and planning practice across the United States. It integrates demographic, economic, social, and urban development indicators with best practices and innovative initiatives to better understand the challenges and opportunities the “silver tsunami” presents for cities, towns, and rural areas.

## Spring 2025

### UP 510: Plan Making Workshop

[Registration Link](https://courses.illinois.edu/schedule/2025/spring/UP/510)

This workshop will develop an update to the [Village of Teutopolis](https://teutopolis.com) Comprehensive Plan. [The Plan](https://teutopolis.com/wp-content/uploads/2023/08/Teutopolis-Comprehensive-Plan-Update-RFP-min.pdf) was last updated in 2011, however given rapid residential and business growth in the community, the Village wants to account for these changes in their plan. Working as a team, we will perform an update to the comprehensive plan including community data collection and analysis. You will facilitate public meetings as well as key stakeholder meetings within the community. Our expected deliverable by the end of the semester is a complete draft comprehensive plan update to be presented to the Village Board.

### UP 591: Capstone Seminar

[Registration Link](https://courses.illinois.edu/schedule/2025/spring/UP/591) - all MUP 2 students should register for 0 credit hours.

The MUP Capstone Seminar is designed to structure and support the early stages of the 2-semester capstone sequence. Over the course of the seminar, students will structure their capstone project or thesis, develop a work plan, and develop a timeline and accountability strategy. By the end of the first semester workshop, students will complete project background work and develop a clear strategy for project completion and dissemination in the second semester. All MUP 2 students take 0 credit hours of workshop in the spring.

### UP 592: Doctoral Urban Planning Seminar

[Registration Link](https://courses.illinois.edu/schedule/2025/spring/UP/592)

The Doctoral Urban Planning seminar is a platform for intellectual development for PhD students in the Department of Urban & Regional Planning and a medium for building a community of scholars. The seminars facilitate the exchange of ideas and perspectives among urban planning Ph.D. students and faculty. The seminar is intended to benefit doctoral students across all stages in their research and doctoral studies, and provides a shared space for students to present their research and to solicit critical, yet constructive, peer reviews and advice.

## Fall 2024

### UP 591: Capstone Seminar

[Registration Link](https://courses.illinois.edu/schedule/2024/fall/UP/591)

The MUP Capstone Seminar is designed to structure and support the early stages of the 2-semester capstone sequence. Over the course of the seminar, students will structure their capstone project or thesis, develop a work plan, and develop a timeline and accountability strategy. By the end of the first semester workshop, students will complete project background work and develop a clear strategy for project completion and dissemination in the second semester. MUP 2 students will either take 0 credit hours of capstone seminar (if pursuing the Workshop capstone option) or 4 credit hours of capstone seminar (if pursuing the Project or Thesis capstone option).

### UP 592: Doctoral Urban Planning Seminar

[Registration Link](https://courses.illinois.edu/schedule/2024/fall/UP/592)

The Doctoral Urban Planning seminar is a platform for intellectual development for PhD students in the Department of Urban & Regional Planning and a medium for building a community of scholars. The seminars facilitate the exchange of ideas and perspectives among urban planning Ph.D. students and faculty. The seminar is intended to benefit doctoral students across all stages in their research and doctoral studies, and provides a shared space for students to present their research and to solicit critical, yet constructive, peer reviews and advice.

## Spring 2024

### UP 570: Neighborhood Analysis

[Course Website](https://up570s24.netlify.app)<br>

Techniques for analyzing the demographic, economic, physical, and social conditions that exist at the neighborhood and local government scale. While our focus will be on analyzing current conditions, we will also learn how to tell stories about neighborhood change, and will learn how to project and forecast future trends. We will learn how to describe community characteristics with small area census data, work with local administrative data, and will learn how to design primary data collection strategies to fill in gaps in knowledge gained through exploration and analysis of existing data.

### UP 592: Doctoral Urban Planning Seminar

[Course Website](https://up592s24.netlify.app)<br>

The Doctoral Urban Planning seminar is a platform for intellectual development for PhD students in the Department of Urban & Regional Planning and a medium for building a community of scholars. The seminars facilitate the exchange of ideas and perspectives among urban planning Ph.D. students and faculty. The seminar is intended to benefit doctoral students across all stages in their research and doctoral studies, and provides a shared space for students to present their research and to solicit critical, yet constructive, peer reviews and advice.

## Fall 2023

### UP 473: Housing and Urban Policy

[Registration Link](https://courses.illinois.edu/schedule/2023/fall/UP/473) </br> [Course Website](https://up473f23.netlify.app) (draft in progress)

Housing represents a fundamental human need and a critical element of human settlements. Within the context of urban planning, housing represents one of the ways in which planning intervention has sought to ensure the health and safety of residents, while also bearing influence on the spatial, social, and economic relationships that differentiate housing and other land uses. Within this class, we will explore the policies and practices that constitute housing policy in the United States and abroad, in order to understand where and how planning strategies have been effective (and ineffective) at shaping physical, economic, social, and political dimensions of housing.

By the end of this course, we will develop:

1.  An understanding of the housing production and regulation system in the United States;
2.  An understanding of historic and contemporary housing policy intervention strategies;
3.  An understanding the intersection between housing policy and other urban policy initiatives;
4.  A framework for evaluation and analysis of housing policies in the US and abroad;
5.  Strategies for effective analysis and communication of housing policy trends and impacts.

### FAA 499 / UP 494: Informing the Illinois Arts Ecosystem

Co-taught with [Jennifer Novak-Leonard](https://urban.illinois.edu/people/profiles/jennifer-novak-leonard/) and [Magdalena Novoa](https://urban.illinois.edu/people/profiles/magdalena-novoa/)

[Registration Link](https://courses.illinois.edu/schedule/2023/fall/UP/494)

This special topics-course is a team-led workshop that will engage students with timely matters and challenges affecting arts and artists across the state of Illinois, and with cultural leaders working to address those challenges. A key tool needed and used by such cultural leaders is research and evidence; hence, in addition to being exposed to current matters affecting the arts ecosystem across the state, students will engage with and work toward producing research and evidence that can help inform the work of cultural leaders. Students will participate in two, one-day trips to Chicago to meet with cultural leaders working to address timely matters and challenges in the city and throughout Illinois. Prior background in either arts or policy is not required to participate in the class.

By the end of the course we will develop:

1.  A better understanding of who artists and creative workers at in Illinois, where they live, and what some of their main characteristics are.
2.  A better understanding of the organizations and institutions who are engaging with and addressing issues that overlap with or impact artists and creative workers.
3.  A detailed understanding of policies directly and indirectly targeting quality of life and stability for artists and creative workers.
4.  Policy-informed research that can inform current debates at the local, state, and federal level around issues related to the arts.

Here are some example policy briefs and issues which will guide our learning this semester:

-   Issue Brief: [The Status of Artists and Creative Workers](https://artsimpact.faa.illinois.edu/research/issue-brief-the-status-of-artists-and-creative-workers/)

-   Issue Brief: [The Artist Labor Force: a statistical look at Illinois in context of the U.S.](https://artsimpact.faa.illinois.edu/research/issue-brief-the-artist-labor-force-a-statistical-look-at-illinois-in-context-of-the-u-s/)

-   Issue Brief: [Housing Affordability for Illinois Artists and Creative Workers (2019--2021)](https://artsimpact.faa.illinois.edu/research/arts-impact-initiative-releases-new-issue-brief-on-chicagos-artist-labor-force-copy/)

-   [Peoria's Cultural Assets: Mapping Resources, People, and Meaning](https://artsimpact.faa.illinois.edu/research/peorias-cultural-assets-mapping-resources-people-and-meaning/) / [Peoria's Cultural Assets Storymap](https://storymaps.arcgis.com/stories/82cb29024ce3465290995b8f6b3ca313)

### UP 592: Doctoral Urban Planning Seminar

[Registration Link](https://courses.illinois.edu/schedule/2023/fall/UP/592)

The Doctoral Urban Planning seminar is a platform for intellectual development for PhD students in the Department of Urban & Regional Planning and a medium for building a community of scholars. The seminars facilitate the exchange of ideas and perspectives among urban planning Ph.D. students and faculty. The seminar is intended to benefit doctoral students across all stages in their research and doctoral studies, and provides a shared space for students to present their research and to solicit critical, yet constructive, peer reviews and advice.

## Spring 2023

### UP 473: Housing and Urban Policy

[Course Website](https://up473s23.netlify.app)

The role of housing in American social policy planning: the history of public and private intervention in housing, regulation of supply and demand within housing markets and market imperfections; analysis of public policies for housing as they affect special populations (for example, the poor, the elderly, the disabled, homeless, and minorities).

### UP 570: Neighborhood Analysis

[Course Website](https://up570s23.netlify.app)

Techniques for analyzing the demographic, economic, physical, and social conditions that exist at the neighborhood and local government scale. While our focus will be on analyzing current conditions, we will also learn how to tell stories about neighborhood change, and will learn how to project and forecast future trends. We will learn how to describe community characteristics with small area census data, work with local administrative data, and will learn how to design primary data collection strategies to fill in gaps in knowledge gained through exploration and analysis of existing data.

## Fall 2022

On sabbatical

## Spring 2022

### UP 473: Housing and Urban Policy

[Course Website](https://housingandurbanpolicy-s22.netlify.app)

## Fall 2021

### UP 101: Introduction to City Planning

### UP 494-AG: Neighborhood Analysis

[Course Website](https://neighborhood-analysis-f21.netlify.app)

## Spring 2021

### UP 494-AG: Neighborhood Analysis

[Course Website](https://neighborhood-analysis-s21.netlify.app)
